# -*- coding: utf-8 -*-
"""All site copy, both languages. Edit here, then run: python3 build.py"""

COPY = {
 "en": {
  "strip_prev": "Previous weddings",
  "strip_next": "More weddings",
  "send_fail_sub": "Something went wrong on the way. Please email me directly at",
  "send_fail": "The message could not be sent.",
  "sent_ok_sub": "I reply within two days, usually sooner.",
  "sent_ok": "Thank you — your enquiry is on its way.",
  "sending": "Sending…",
  "album_back": "All work",
  "album_eyebrow": "Album",
  "album_lede": "Every photograph from this wedding. Press any of them to open it full size.",
  "albums_h": "Weddings",
  "work_album_hint": "Press a photograph to open that wedding's album.",
  "see_album": "See the whole album",
  "photos_count": "photographs",
  "home_title": "Hiroki Filmuje — wedding films and photography",
  "home_desc": "Wedding films and photography. One person, the whole day, no posing drills. Films ready within 14 days.",
  "hero_eyebrow": "Wedding films &amp; photography",
  "hero_h1": 'The day as it<br><span class="ital">actually</span> happened',
  "hero_lede": "I work alone, quietly, with a camera in my hands all day. No posing drills — your wedding, kept the way it felt.",
  "hero_cta1": "Check your date", "hero_cta2": "See the work",
  "s1_rail1": "01 — Approach", "s1_rail2": "Solo",
  "s1_h": "One person, one eye, the whole day.",
  "s1_p1": "Working solo means the film and the photographs come from the same pair of eyes. The colour, the rhythm, the moments I go after — all of it stays consistent from the first frame to the last.",
  "s1_p2": "I stay out of the way. Wide and quiet for most of the day, close only when something is happening that deserves it. The one thing I ask for is a short walk near golden hour.",
  "spec": [("Coverage","Film and photography"),("Crew","Solo"),("Film ready","Within 14 days"),("Delivery","WeTransfer or Google Drive")],
  "s2_rail1": "02 — Selected", "s2_rail2": "Recent",
  "s2_h": "Frames from recent weddings", "s2_btn": "Full portfolio",
  "strip_note": "Drag or scroll sideways",
  "s3_eyebrow": "04 — Behind the camera",
  "s3_h": "Hi, I'm Hiroki.",
  "s3_p1": "I film and photograph weddings in Poland. I came to this work because I like watching people forget the camera is there — and because a wedding is one of the few days when everyone in the room is telling the truth.",
  "s3_p2": "I cover the whole day myself: the preparations, the ceremony, the party until the dance floor finds its level. Then I cut it into a film you will actually rewatch.",
  "s3_btn": "More about me",
  "s4_eyebrow": "03 — In their words",
  "quote_note": "Translated from the original Polish messages.",
  "cta_h": "Dates book well ahead. Tell me when and where.",
  "cta_btn": "Start an enquiry",

  "work_title": "Work — Hiroki Filmuje",
  "work_desc": "Wedding films and photographs from recent weddings.",
  "work_h1": "Work",
  "work_lede": "Films and photographs from recent weddings. Press any photograph to open it full size.",
  "tab_all": "Everything", "tab_film": "Films", "tab_photo": "Photographs",
  "films_h": "Films", "photos_h": "Photographs",
  "work_rail1": "Portfolio", "work_rail2": "Film &amp; stills",

  "about_title": "About me — Hiroki Filmuje",
  "about_desc": "Hiroki Filmuje — wedding filmmaker and photographer working solo across Poland.",
  "about_h1": "About me",
  "about_eyebrow": "Behind the camera",
  "about_lede": "I'm Hiroki. I film and photograph weddings, and I do both myself.",
  "about_p1": "Working solo is a deliberate choice, not a limitation. One person carrying both the camera and the stills means the film and the photographs share a look: the same colour, the same instinct about when to step closer and when to leave people alone.",
  "about_p2": "I am not interested in a wedding that has been arranged for the lens. The parts worth keeping tend to happen on their own — someone's father going quiet during the speeches, the half-second before a first dance starts, a room that has been laughing for an hour and does not realise it. My job is to be there for those, and to be unobtrusive enough that they still happen.",
  "about_p3": "In practice that means I am there from the preparations through to the dancing. I shoot in the light the day gives me. I ask for one short walk near golden hour, and that is the only part of the day I will direct.",
  "about_p4": "Afterwards I edit everything myself. The film is with you within 14 days, delivered as a download link over WeTransfer or Google Drive.",
  "about_steps_h": "How a day runs",
  "about_steps": [
    ("A message and a call", "Tell me the date and the place. We talk for twenty minutes about how the day is shaped — no sales pitch."),
    ("The date is held", "A signed agreement and a 30% deposit take the date out of the calendar."),
    ("The wedding day", "I arrive during the preparations and stay through the ceremony and the reception. One short portrait walk, timed to the light."),
    ("Edit and delivery", "I cut, grade and finish the film myself. It reaches you within 14 days by WeTransfer or Google Drive."),
  ],

  "offer_title": "Offer — Hiroki Filmuje",
  "offer_desc": "Wedding film packages from 3 000 zł. Highlight films, full-day coverage, drone, Instagram Reel.",
  "offer_h1": "Offer",
  "offer_lede": "Three film packages. Every one of them is shot, edited and graded by me.",
  "offer_rail1": "Packages", "offer_rail2": "Prices in zł",
  "extras_h": "Extras",
  "extras": [("Drone", "+500 zł — aerial shots cut into the final film"),
             ("Additional outdoor session", "Quoted individually")],
  "general_h": "The practical part",
  "general": [("Crew","I work solo — one consistent style across the whole film"),
              ("Turnaround","Finished film within 14 days of the wedding"),
              ("Delivery","Download link via WeTransfer or Google Drive"),
              ("Travel","Depends on the distance — ask me for a figure")],
  "pay_h": "Payment",
  "pay_intro": "Cash, in three parts:",
  "pay": [("30%","On signing the agreement — this reserves your date"),
          ("50%","On the wedding day"),
          ("20%","After the finished film is delivered")],
  "offer_close": "Happy to send more examples of my work or answer anything that is not covered here.",

  "contact_title": "Contact — Hiroki Filmuje",
  "contact_desc": "Enquire about your wedding date. Email sebasuta@gmail.com or +48 516 849 121.",
  "contact_h1": "Let's talk",
  "contact_lede": "The date and the place are enough to start. Everything else we can work out on a call.",
  "contact_rail1": "Enquire", "contact_rail2": "Usually a reply within 2 days",
  "f_name": "Your names", "f_name_ph": "both of you, if you like",
  "f_email": "Email", "f_email_ph": "where I should reply",
  "f_date": "Wedding date", "f_date_note": "Leave blank if it is not fixed yet",
  "f_place": "Where", "f_place_ph": "venue, town, or just the region",
  "f_cov": "What you are after",
  "f_cov_opts": ["Choose one","Film only","Film and photography","Photography only","Not sure yet"],
  "f_notes": "Anything else", "f_notes_ph": "How the day runs, what matters most, anything you are worried about.",
  "f_send": "Send enquiry",
  "form_note": "Your details come straight to my inbox and go nowhere else.",
  "direct_h": "Or reach me directly",
  "l_email": "Email", "l_phone": "Phone", "l_ig": "Instagram",
  "copy": "Copy",
  "faq_h": "Before you ask",
  "faq": [
    ("How far do you travel?", "Travel is quoted according to distance, so tell me where the wedding is and I will give you a figure with the package price."),
    ("How long until we get the film?", "Within 14 days of the wedding. You get a download link over WeTransfer or Google Drive."),
    ("Do you work alone?", "Yes. One person for the film and the photographs, which is what keeps the style consistent across the whole day."),
    ("Can we choose the music?", "Yes — one song of your choice is part of every package."),
    ("How do we book?", "A signed agreement and a 30% deposit reserve the date. 50% is paid on the wedding day and the last 20% once the finished film is delivered."),
  ],
 },

 "pl": {
  "strip_prev": "Poprzednie śluby",
  "strip_next": "Kolejne śluby",
  "send_fail_sub": "Coś poszło nie tak po drodze. Proszę napisać bezpośrednio na adres",
  "send_fail": "Nie udało się wysłać wiadomości.",
  "sent_ok_sub": "Odpowiadam w ciągu dwóch dni, zwykle szybciej.",
  "sent_ok": "Dziękuję — zapytanie zostało wysłane.",
  "sending": "Wysyłanie…",
  "album_back": "Całe portfolio",
  "album_eyebrow": "Album",
  "album_lede": "Wszystkie zdjęcia z tego ślubu. Kliknijcie dowolne, aby otworzyć je w pełnym rozmiarze.",
  "albums_h": "Śluby",
  "work_album_hint": "Kliknijcie zdjęcie, aby otworzyć album z tego ślubu.",
  "see_album": "Zobacz cały album",
  "photos_count": "zdjęć",
  "home_title": "Hiroki Filmuje — filmy i fotografia ślubna",
  "home_desc": "Filmy i fotografia ślubna. Jedna osoba, cały dzień, bez sztucznego pozowania. Gotowy film do 14 dni.",
  "hero_eyebrow": "Filmy i fotografia ślubna",
  "hero_h1": 'Dzień taki,<br>jaki był <span class="ital">naprawdę</span>',
  "hero_lede": "Pracuję sam, po cichu, z aparatem w ręku przez cały dzień. Bez sztucznego pozowania — zostaje Wasz ślub taki, jaki był.",
  "hero_cta1": "Sprawdź termin", "hero_cta2": "Zobacz prace",
  "s1_rail1": "01 — Podejście", "s1_rail2": "Solo",
  "s1_h": "Jedna osoba, jedno spojrzenie, cały dzień.",
  "s1_p1": "Pracuję solo, więc film i zdjęcia powstają z tej samej perspektywy. Kolor, rytm, wyłapywane momenty — wszystko jest spójne od pierwszego do ostatniego kadru.",
  "s1_p2": "Nie wchodzę w drogę. Przez większość dnia jestem z boku, podchodzę bliżej tylko wtedy, gdy dzieje się coś, co na to zasługuje. Proszę jedynie o krótki spacer o złotej godzinie.",
  "spec": [("Zakres","Film i fotografia"),("Obsada","Solo"),("Gotowy film","Do 14 dni"),("Dostawa","WeTransfer lub Google Drive")],
  "s2_rail1": "02 — Wybrane", "s2_rail2": "Ostatnie",
  "s2_h": "Kadry z ostatnich ślubów", "s2_btn": "Całe portfolio",
  "strip_note": "Przeciągnij lub przewiń w bok",
  "s3_eyebrow": "04 — Za kamerą",
  "s3_h": "Cześć, jestem Hiroki.",
  "s3_p1": "Filmuję i fotografuję śluby w Polsce. Zajmuję się tym, bo lubię patrzeć, jak ludzie zapominają o kamerze — i dlatego, że ślub jest jednym z niewielu dni, kiedy wszyscy na sali są prawdziwi.",
  "s3_p2": "Cały dzień obsługuję sam: przygotowania, ceremonię i wesele, aż parkiet złapie swój rytm. Potem montuję z tego film, do którego naprawdę się wraca.",
  "s3_btn": "Poznaj mnie",
  "s4_eyebrow": "03 — Opinie",
  "quote_note": "Oryginalne wiadomości od par młodych.",
  "cta_h": "Terminy rezerwują się z dużym wyprzedzeniem. Napiszcie, kiedy i gdzie.",
  "cta_btn": "Napisz do mnie",

  "work_title": "Portfolio — Hiroki Filmuje",
  "work_desc": "Filmy i zdjęcia z ostatnich ślubów.",
  "work_h1": "Portfolio",
  "work_lede": "Filmy i zdjęcia z ostatnich ślubów. Kliknijcie zdjęcie, aby otworzyć je w pełnym rozmiarze.",
  "tab_all": "Wszystko", "tab_film": "Filmy", "tab_photo": "Zdjęcia",
  "films_h": "Filmy", "photos_h": "Zdjęcia",
  "work_rail1": "Portfolio", "work_rail2": "Film i zdjęcia",

  "about_title": "O mnie — Hiroki Filmuje",
  "about_desc": "Hiroki Filmuje — filmy i fotografia ślubna. Pracuję solo, w całej Polsce.",
  "about_h1": "O mnie",
  "about_eyebrow": "Za kamerą",
  "about_lede": "Jestem Hiroki. Filmuję i fotografuję śluby — jedno i drugie robię osobiście.",
  "about_p1": "Praca solo to świadomy wybór, nie ograniczenie. Jedna osoba z kamerą i aparatem oznacza, że film i zdjęcia mają ten sam charakter: ten sam kolor i to samo wyczucie, kiedy podejść bliżej, a kiedy zostawić ludziom przestrzeń.",
  "about_p2": "Nie interesuje mnie ślub ustawiony pod obiektyw. To, co warto zatrzymać, dzieje się samo — tata, który milknie w trakcie przemówienia, pół sekundy przed pierwszym tańcem, sala, która śmieje się od godziny i nawet tego nie zauważa. Moim zadaniem jest przy tym być i nie przeszkadzać, żeby to dalej się działo.",
  "about_p3": "W praktyce jestem z Wami od przygotowań aż po tańce. Pracuję w świetle, które daje dzień. Proszę o jeden krótki spacer o złotej godzinie — i to jedyny moment, który reżyseruję.",
  "about_p4": "Całość montuję sam. Gotowy film trafia do Was w ciągu 14 dni, jako link do pobrania przez WeTransfer lub Google Drive.",
  "about_steps_h": "Jak wygląda współpraca",
  "about_steps": [
    ("Wiadomość i rozmowa", "Napiszcie termin i miejsce. Rozmawiamy dwadzieścia minut o tym, jak wygląda Wasz dzień — bez sprzedażowego gadania."),
    ("Rezerwacja terminu", "Podpisana umowa i 30% zaliczki blokują termin w kalendarzu."),
    ("Dzień ślubu", "Przyjeżdżam na przygotowania i zostaję przez ceremonię i wesele. Jeden krótki plener, dopasowany do światła."),
    ("Montaż i dostawa", "Montuję, koloruję i kończę film osobiście. Dostajecie go do 14 dni przez WeTransfer lub Google Drive."),
  ],

  "offer_title": "Oferta — Hiroki Filmuje",
  "offer_desc": "Pakiety filmów ślubnych od 3 000 zł. Highlight, pełny dzień, dron, Reel na Instagram.",
  "offer_h1": "Oferta",
  "offer_lede": "Trzy pakiety filmowe. Każdy z nich nagrywam, montuję i koloruję osobiście.",
  "offer_rail1": "Pakiety", "offer_rail2": "Ceny w zł",
  "extras_h": "Dodatki",
  "extras": [("Dron", "+500 zł — ujęcia lotnicze zmontowane w finalny film"),
             ("Dodatkowa sesja plenerowa", "Wycena indywidualna")],
  "general_h": "Informacje ogólne",
  "general": [("Obsada","Pracuję solo — pełna spójność stylu i estetyki przez cały film"),
              ("Czas realizacji","Gotowy film do 14 dni od ślubu"),
              ("Forma dostawy","Link do pobrania przez WeTransfer lub Google Drive"),
              ("Dojazd","Zależny od odległości — napiszcie, gdzie się odbywa ślub")],
  "pay_h": "Płatność",
  "pay_intro": "Gotówka, w trzech częściach:",
  "pay": [("30%","Przy podpisaniu umowy — rezerwacja terminu"),
          ("50%","W dniu ślubu"),
          ("20%","Po dostarczeniu gotowego materiału")],
  "offer_close": "Chętnie prześlę przykłady mojej pracy lub odpowiem na dodatkowe pytania.",

  "contact_title": "Kontakt — Hiroki Filmuje",
  "contact_desc": "Zapytaj o termin. E-mail sebasuta@gmail.com lub +48 516 849 121.",
  "contact_h1": "Napiszcie do mnie",
  "contact_lede": "Termin i miejsce w zupełności wystarczą na początek. Resztę ustalimy na rozmowie.",
  "contact_rail1": "Kontakt", "contact_rail2": "Odpowiadam zwykle w 2 dni",
  "f_name": "Wasze imiona", "f_name_ph": "najlepiej oboje",
  "f_email": "E-mail", "f_email_ph": "adres, na który mam odpowiedzieć",
  "f_date": "Data ślubu", "f_date_note": "Zostawcie puste, jeśli termin nie jest jeszcze ustalony",
  "f_place": "Miejsce", "f_place_ph": "sala, miasto albo sam region",
  "f_cov": "Czego potrzebujecie",
  "f_cov_opts": ["Wybierzcie","Tylko film","Film i zdjęcia","Tylko zdjęcia","Jeszcze nie wiemy"],
  "f_notes": "Coś jeszcze", "f_notes_ph": "Jak wygląda dzień, co jest dla Was najważniejsze, o co się martwicie.",
  "f_send": "Wyślij zapytanie",
  "form_note": "Wasze dane trafiają prosto na moją skrzynkę i nigdzie indziej.",
  "direct_h": "Albo bezpośrednio",
  "l_email": "E-mail", "l_phone": "Telefon", "l_ig": "Instagram",
  "copy": "Kopiuj",
  "faq_h": "Zanim zapytacie",
  "faq": [
    ("Jak daleko dojeżdżasz?", "Dojazd wyceniam według odległości — napiszcie, gdzie odbywa się ślub, a podam kwotę razem z ceną pakietu."),
    ("Kiedy dostaniemy film?", "Do 14 dni od ślubu. Dostajecie link do pobrania przez WeTransfer lub Google Drive."),
    ("Pracujesz sam?", "Tak. Jedna osoba do filmu i do zdjęć — dzięki temu całość jest spójna stylistycznie."),
    ("Czy możemy wybrać muzykę?", "Tak — jedna piosenka według Waszego wyboru wchodzi w skład każdego pakietu."),
    ("Jak zarezerwować termin?", "Podpisana umowa i 30% zaliczki rezerwują termin. 50% płatne w dniu ślubu, ostatnie 20% po dostarczeniu gotowego filmu."),
  ],
 },
}

